# Применение существующих моделей LID на золотом стандарте

Результаты будут проанализированы на двух задачах -- выявление нерелевантных одноязычных текстов и выявление csw в тексте.

Анализируемые методы:
- cld2
- cld3
- fast-langdetect
- lingua
- mediapipe
- fasttext (nllb)
- glotlid
- словарный метод

Методы применялись и анализировались на датасете KazRusCSW-G-T, который мы разметили вручную на уровне текста. Для этого мы отобрали 10 тыс. примеров с обеих платформ (2 telegram-канала и 1 youtube-канал). В процессе разметки встречались комментарии, которые не подходили в силу большого количества орфографических ошибок, неоднозначности языковой принадлежности или чрезмерной грубости -- от них мы избавлялись, что оставило нас с 9700 примерами.

Тегсет включал 4 тега, которые могли комбинироваться друг с другом:
- kz -- комментарий содержит слова казахского языка;
- skz -- комментарий содержит слова казахского языка, написанные с заменой специализированных символов казахского языка;
- ru -- комментарий содержит слова казахского языка;
- unk -- комментарий содержит слова на другом языке (английский, немецкий, якутский и т.д.).

ВАЖНО: блокнот удобнее всего будет запускать в google colab, т.к. меньше проблем с установкой зависимостей (а их много!)

In [1]:
import seaborn as sns
from matplotlib import pyplot as plt
import ast
import pandas as pd
import math

class Experiment:
    def __init__(self, df, method):
        self.df = df
        self.method = method

    def add_probas(self, df_langproba, dropped_cols):
        self.df.drop(columns=df_langproba.columns, errors='ignore', inplace=True)
        self.df = pd.concat([self.df, df_langproba.drop(columns=dropped_cols)], axis=1)
        self.fillna_0()

    def fillna_0(self):
        new_cols = self.df.filter(regex=self.method).select_dtypes(include=['float64']).columns

        self.df[new_cols] = self.df[new_cols].fillna(0)

    def visualize_probas(self, target_col='manual_tag'):
        sns.set()

        fig, axes = plt.subplots(1, 2,figsize=(10,5))
        axes = axes.flatten()

        sns.set(style='whitegrid')

        sns.scatterplot(ax=axes[0], data=self.df, x=f'{self.method}__kaz', y=f'{self.method}__rus', hue=target_col)

        sns.kdeplot(ax=axes[1], data=self.df[[f'{self.method}__kaz', f'{self.method}__rus']])

        fig.suptitle(self.method)

    def save_experiment(self, path):
        self.df.to_csv(path, index=False)

def visualize_tags(df, method, manual_col='manual_tag', x_lang='kaz', y_lang='rus'):
    sns.set()

    nrows = math.ceil(len(df[manual_col].unique())/2)

    fig, axes = plt.subplots(nrows, 2, sharex=True, sharey=True,figsize=(10,nrows*5))
    axes = axes.flatten()

    sns.set(style='whitegrid')

    for i, tag in enumerate(df[manual_col].unique()):
        sns.scatterplot(ax=axes[i], data=df[df[manual_col]==tag], x=f'{method}__{x_lang}', y=f'{method}__{y_lang}')
        axes[i].set_title(tag)

    fig.suptitle(f'Распределение тегов {x_lang}, {y_lang}, полученных с помощью {method}')

In [2]:
def sort_labels(lst):
    order = {
        'lat_kz': 0,
        'kz': 1,
        'skz': 2,
        'ru': 3,
        'en': 4,
        'unk': 5,
    }
    return sorted(lst, key=order.get)

In [3]:
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report, accuracy_score, precision_recall_curve
from sklearn.metrics import f1_score

import pandas as pd
import numpy as np

In [4]:
sheet_id = "1pIV0z6GWbt_xTweBXHIUXmU4K-84XiTseFbobv7K_xE"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

df = pd.read_csv(url, usecols=['text', 'manual_tag'])
df.head()

                                                text manual_tag
0  “Сандж” тәуелсіз зерттеу орталығының хабарлауы...         kz
1  Заңгер Алексей Сонның консультациясына мына сі...         kz
2  Шымкентте елуге жуық әйел әкімдік алдына жинал...         kz
3  Өте маңызды жобаға сұхбат кейіпкері ретінде кі...         kz
4  Айсұлтанның “құпиясы” Британиялық Financial ti...     kz-unk

In [5]:
# выкидываем маски
df['text'] = df['text'].str.replace(r'\[[A-Z]+\]', '', regex=True)

In [6]:
save_to_path = 'filtering_experiments.csv'

### Compact Language Detector 2
Репозиторий: https://github.com/CLD2Owners/cld2

Поддерживает 83 языка. Модель представляет собой Naïve Bayesian classifier на основе n-грамм: для казахского и русского предсказания делаются на основе квадграмм(4-грамм). В первую очередь cld2 приводит текст к нижнему регистру, удаляет цифры, пунктуацию и HTML-теги.

#### Обработка

In [7]:
!pip install pyicu pycld2 morfessor

Collecting pyicu
  Downloading pyicu-2.16.2.tar.gz (268 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.2/268.2 kB 6.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycld2
  Downloading pycld2-0.42-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
Collecting morfessor
  Downloading Morfessor-2.0.6-py3-none-any.whl.metadata (628 bytes)
Downloading pycld2-0.42-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 74.0 MB/s eta 0:00:00
Downloading Morfessor-2.0.6-py3-none-any.whl (35 kB)
Building wheels for collected packages: pyicu
  Building wheel for pyicu (pyproject.toml) ... done
  Created wheel for pyicu: filename=pyicu-2.16.2-cp312-cp312-linux_x86_64.whl size=2720233 sha256=2e5b478bd5b055edd3935ace57b493d331a6a523781138a086f6702d7e35bfba
  Stored in directory: /root/.cache/pip/wheels/25/f3/cd/4923c874cedf8cdb8608035f48bb726fa040a98a66e2b13cea
Successfully built pyicu
Installing collected packages: pyicu, pycld2, morfessor
Successfully installed morfessor-2.0.6 pycld2-0.42 pyicu-2.16.2

In [8]:
import pandas as pd

METHOD = 'cld2'
exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

                                                text manual_tag
0  “Сандж” тәуелсіз зерттеу орталығының хабарлауы...         kz
1  Заңгер Алексей Сонның консультациясына мына сі...         kz
2  Шымкентте елуге жуық әйел әкімдік алдына жинал...         kz
3  Өте маңызды жобаға сұхбат кейіпкері ретінде кі...         kz
4  Айсұлтанның “құпиясы” Британиялық Financial ti...     kz-unk

In [15]:
import pycld2 as cld2

lang_dict = {
    'kk': 'kz',
    'ru': 'ru',
}

def cld2__sentence_level(text):
    """
    CLD2 определяет три наиболее вероятных языка.

    Возвращает три объекта:
    - строку из найденных языков, которые расположены в строго определенном порядке kz/skz -> ru -> unk
    - тег языка, который определен как более вероятный
    - вероятности kz, ru, unk
    """
    isReliable, textBytesFound, details = cld2.detect(text)
    dct_all = {l[1]: l[2]/100 for l in details}

    best_lang = details[0][1]

    dct = dict()
    for l in ('kk', 'ru'):
        dct[l] = dct_all.get(l, 0)

    res = []
    # print(details)
    for d in details:
        if d[2]>0:
            if lang_dict.get(d[1]):
                res.append(lang_dict[d[1]])
            else:
                # print(d)
                res.append('unk')

    if not res:
        res = ['unk']

    return '-'.join(sort_labels(set(res))), best_lang, dct

s = 'Білім саласына қатысты сұрақтар бойынша жедел желі нөмірлері. Номера горячей линии по вопросам образования'
cld2__sentence_level(text=s)

('kz-ru', 'kk', {'kk': 0.5, 'ru': 0.49})

In [13]:
df_langproba = pd.DataFrame(index=exprmnt.df.index)

df_langproba[[f'{METHOD}__all_langs', f'{METHOD}__best_lang', f'{METHOD}__probas']] = exprmnt.df['text'].apply(cld2__sentence_level).tolist()
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    'kk': f'{METHOD}__kaz',
    'ru': f'{METHOD}__rus',
}, inplace=True)
df_langproba[f'{METHOD}__best_lang'].replace({'kk': 'kz'}, inplace=True)

/tmp/ipykernel_2463/4103955081.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_langproba[f'{METHOD}__best_lang'].replace({'kk': 'kz'}, inplace=True)

In [14]:
df_langproba

     cld2__all_langs cld2__best_lang             cld2__probas
0                 kz              kz  {'kk': 0.99, 'un': 0.0}
1                 kz              kz  {'kk': 0.99, 'un': 0.0}
2                 kz              kz  {'kk': 0.99, 'un': 0.0}
3                 kz              kz  {'kk': 0.99, 'un': 0.0}
4                 kz              kz  {'kk': 0.98, 'un': 0.0}
...              ...             ...                      ...
9694              kz              kz  {'kk': 0.99, 'un': 0.0}
9695              kz              kz  {'kk': 0.99, 'un': 0.0}
9696              kz              kz  {'kk': 0.99, 'un': 0.0}
9697             unk              un              {'un': 0.0}
9698              kz              kz  {'kk': 0.98, 'un': 0.0}

[9699 rows x 3 columns]

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=[f'{METHOD}__probas'])

In [ ]:
exprmnt.df[f'{METHOD}__all_langs'].value_counts()

cld2__all_langs
ru           4892
kz           3498
unk          1003
ru-unk        143
kz-unk        111
kz-ru          49
kz-ru-unk       3
Name: count, dtype: int64

In [ ]:
exprmnt.df[[f'{METHOD}__kaz', f'{METHOD}__rus']].describe()

         cld2__kaz    cld2__rus
count  9699.000000  9699.000000
mean      0.362215     0.490162
std       0.468461     0.476291
min       0.000000     0.000000
25%       0.000000     0.000000
50%       0.000000     0.590000
75%       0.980000     0.980000
max       0.990000     0.990000

In [ ]:
exprmnt.df['cld2__best_lang'].value_counts()

cld2__best_lang
ru    4984
kz    3621
un     848
sr     102
ky      88
uz      19
uk      12
tk       8
bg       5
mn       3
en       3
de       1
mk       1
tg       1
ro       1
ug       1
tt       1
Name: count, dtype: int64

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
df = exprmnt.df

### Compact Language Detector 3
Репозиторий: https://github.com/google/cld3

cld3 разработан для Chrome-браузера, на сегодняшний день существует как публичный архив.

#### Обработка

In [ ]:
METHOD = 'cld3'
exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0

In [ ]:
!sudo apt-get install -y --no-install-recommends g++ protobuf-compiler libprotobuf-dev

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
g++ is already the newest version (4:11.2.0-1ubuntu1).
libprotobuf-dev is already the newest version (3.12.4-1ubuntu7.22.04.6).
protobuf-compiler is already the newest version (3.12.4-1ubuntu7.22.04.6).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

In [ ]:
!pip install gcld3

Collecting gcld3
  Downloading gcld3-3.0.13.tar.gz (647 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.8/647.8 kB 9.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gcld3
  Building wheel for gcld3 (setup.py) ... done
  Created wheel for gcld3: filename=gcld3-3.0.13-cp312-cp312-linux_x86_64.whl size=4002758 sha256=51a0303670cdc236d134e646de98910edee2d1cbd708957880b3470e99a43647
  Stored in directory: /root/.cache/pip/wheels/8e/3c/60/7396eb26af0ae770fe9a54d3c4fcb7b54e03919827c488db87
Successfully built gcld3
Installing collected packages: gcld3
Successfully installed gcld3-3.0.13

In [ ]:
import gcld3

detector = gcld3.NNetLanguageIdentifier(min_num_bytes=0, max_num_bytes=1000)

def cld3__sentence_level(text):
    """
    Возвращает два объекта:
    - тег языка, который определен как более вероятный
    - вероятности kz, ru
    """
    res = detector.FindTopNMostFreqLangs(text=text, num_langs=100)
    dct_all = {l.language: l.probability for l in res}

    best_lang = res[0].language

    dct = dict()
    for l in ('kk', 'ru'):
        prob = dct_all.get(l)
        if prob:
            dct[l] = prob
    return best_lang, dct

s = 'Білім саласына қатысты сұрақтар бойынша жедел желі нөмірлері. Номера горячей линии по вопросам образования'
cld3__sentence_level(text=s)

('kk', {'kk': 0.9742560982704163})

In [ ]:
df_langproba = pd.DataFrame(index=exprmnt.df.index)

df_langproba[[f'{METHOD}__best_lang', f'{METHOD}__probas']] = exprmnt.df['text'].apply(cld3__sentence_level).tolist()
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    'kk': f'{METHOD}__kaz',
    'ru': f'{METHOD}__rus',
}, inplace=True)

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=[f'{METHOD}__probas'])

In [ ]:
exprmnt.df[[f'{METHOD}__kaz', f'{METHOD}__rus']].describe()

         cld3__kaz    cld3__rus
count  9699.000000  9699.000000
mean      0.362240     0.562675
std       0.478067     0.486389
min       0.000000     0.000000
25%       0.000000     0.000000
50%       0.000000     0.974706
75%       0.999937     0.999922
max       1.000000     1.000000

In [ ]:
exprmnt.df['cld3__best_lang'].value_counts()

cld3__best_lang
ru         5545
kk         3529
ky          279
bg           87
uk           77
be           66
sr           52
mn           22
mk           16
tg           11
en            4
sv            2
hi-Latn       2
sm            1
so            1
uz            1
pt            1
ga            1
st            1
fr            1
Name: count, dtype: int64

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
df = exprmnt.df

### LangID

https://github.com/saffsd/langid.py (новая версия: https://github.com/adbar/py3langid)

Модель возвращает логиты.

#### Обработка

In [ ]:
!pip3 install py3langid

Collecting py3langid
  Downloading py3langid-0.3.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from py3langid) (2.0.2)
Downloading py3langid-0.3.0-py3-none-any.whl (746 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 746.1/746.1 kB 10.9 MB/s eta 0:00:00
Installing collected packages: py3langid
Successfully installed py3langid-0.3.0

In [ ]:
METHOD = 'langid'
exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0

In [ ]:
import py3langid as langid

text = 'This text is in English.'

# предсказать наиболее вероятный язык
langid.classify(text)

('en', np.float32(-56.77429))

In [ ]:
# получить сортированный список языков
res = langid.rank(text)
res[:5]

[('en', np.float32(-56.77429)),
 ('la', np.float32(-73.15924)),
 ('af', np.float32(-77.42682)),
 ('br', np.float32(-77.45833)),
 ('nl', np.float32(-80.20705))]

In [ ]:
from py3langid.langid import LanguageIdentifier, MODEL_FILE

identifier = LanguageIdentifier.from_pickled_model(MODEL_FILE, norm_probs=True)

In [ ]:
def langid__sentence_level(text):
    res = langid.rank(text)
    dct = dict()

    for l, logit in res:
        if l in ('kk', 'ru'):
            dct[l] = logit

    if res[0][1] == 0:
        best_lang = 'unk'
    else:
        best_lang = res[0][0]

    return best_lang, dct

df_langproba = pd.DataFrame(index=exprmnt.df.index)

df_langproba[[f'{METHOD}__best_lang', f'{METHOD}__probas']] = exprmnt.df['text'].apply(langid__sentence_level).apply(pd.Series)
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    'kk': f'{METHOD}__kaz',
    'ru': f'{METHOD}__rus',
}, inplace=True)

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=[f'{METHOD}__probas'])

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
exprmnt.df['langid__best_lang'].value_counts()

langid__best_lang
ru    5625
kk    3536
bg     197
uk     122
sr      82
mk      73
be      29
mn      18
ky      15
la       2
Name: count, dtype: int64

In [ ]:
df = exprmnt.df

### Lingua
Репозиторий: https://pypi.org/project/lingua-language-detector/

Модель допускает многоязычность текста и может разбивать текст на участки по языкам, на которых они написаны.

#### Обработка

In [ ]:
METHOD = 'lingua'

exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus,langid__best_lang,langid__kaz,langid__rus
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0,kk,-6629.133789,-7293.619141
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0,kk,-9796.718750,-10485.810547
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0,kk,-2515.423340,-2864.809570
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0,kk,-3253.132324,-3682.371826
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0,kk,-9981.612305,-10986.610352

In [ ]:
!pip install lingua-language-detector

Requirement already satisfied: lingua-language-detector in /usr/local/lib/python3.12/dist-packages (2.2.0)

In [ ]:
from lingua import Language, LanguageDetectorBuilder

languages = [Language.KAZAKH, Language.RUSSIAN, Language.ENGLISH]
# detector = LanguageDetectorBuilder.from_languages(*languages).build()
detector = LanguageDetectorBuilder.from_all_languages().with_preloaded_language_models().build()

def test_lingua(text):
    res = detector.compute_language_confidence_values(text)
    dct = {l.language.name: l.value for l in res}

    if res[0].value == 0:
        best_lang = 'unk'
        dct[best_lang] = 1.0
    else:
        best_lang = res[0].language.name
    return best_lang, dct

s = 'Білім саласына қатысты сұрақтар бойынша жедел желі нөмірлері. Номера горячей линии по вопросам образования'
test_lingua(text=s)

('KAZAKH',
 {'KAZAKH': 1.0,
  'AFRIKAANS': 0.0,
  'ALBANIAN': 0.0,
  'ARABIC': 0.0,
  'ARMENIAN': 0.0,
  'AZERBAIJANI': 0.0,
  'BASQUE': 0.0,
  'BELARUSIAN': 0.0,
  'BENGALI': 0.0,
  'BOKMAL': 0.0,
  'BOSNIAN': 0.0,
  'BULGARIAN': 0.0,
  'CATALAN': 0.0,
  'CHINESE': 0.0,
  'CROATIAN': 0.0,
  'CZECH': 0.0,
  'DANISH': 0.0,
  'DUTCH': 0.0,
  'ENGLISH': 0.0,
  'ESPERANTO': 0.0,
  'ESTONIAN': 0.0,
  'FINNISH': 0.0,
  'FRENCH': 0.0,
  'GANDA': 0.0,
  'GEORGIAN': 0.0,
  'GERMAN': 0.0,
  'GREEK': 0.0,
  'GUJARATI': 0.0,
  'HEBREW': 0.0,
  'HINDI': 0.0,
  'HUNGARIAN': 0.0,
  'ICELANDIC': 0.0,
  'INDONESIAN': 0.0,
  'IRISH': 0.0,
  'ITALIAN': 0.0,
  'JAPANESE': 0.0,
  'KOREAN': 0.0,
  'LATIN': 0.0,
  'LATVIAN': 0.0,
  'LITHUANIAN': 0.0,
  'MACEDONIAN': 0.0,
  'MALAY': 0.0,
  'MAORI': 0.0,
  'MARATHI': 0.0,
  'MONGOLIAN': 0.0,
  'NYNORSK': 0.0,
  'PERSIAN': 0.0,
  'POLISH': 0.0,
  'PORTUGUESE': 0.0,
  'PUNJABI': 0.0,
  'ROMANIAN': 0.0,
  'RUSSIAN': 0.0,
  'SERBIAN': 0.0,
  'SHONA': 0.0,
  'SLOVAK': 0.0,
  'SLOVENE': 0.0,
  'SOMALI': 0.0,
  'SOTHO': 0.0,
  'SPANISH': 0.0,
  'SWAHILI': 0.0,
  'SWEDISH': 0.0,
  'TAGALOG': 0.0,
  'TAMIL': 0.0,
  'TELUGU': 0.0,
  'THAI': 0.0,
  'TSONGA': 0.0,
  'TSWANA': 0.0,
  'TURKISH': 0.0,
  'UKRAINIAN': 0.0,
  'URDU': 0.0,
  'VIETNAMESE': 0.0,
  'WELSH': 0.0,
  'XHOSA': 0.0,
  'YORUBA': 0.0,
  'ZULU': 0.0})

In [ ]:
detector = LanguageDetectorBuilder.from_all_languages().with_preloaded_language_models().build()

def lingua__sentence_level(res):
    """
    Функция принимает результат работы модели (вероятности), полученный в результате параллельных вычислений.
    Возвращает наиболее вероятный язык и вероятности для 'KAZAKH', 'RUSSIAN'
    """
    # res = detector.compute_language_confidence_values(text)
    if type(res)!=list:
        return 'unk', None
    dct = dict()

    if res[0].value == 0:
        best_lang = 'unk'
        # dct[best_lang] = 1.0
    else:
        for l in res:
            if l.language.name in ('KAZAKH', 'RUSSIAN'):
                dct[l.language.name] = l.value
        best_lang = res[0].language.name
    return best_lang, dct

In [ ]:
lang_dict = {
    'KAZAKH': 'kz',
    'RUSSIAN': 'ru',
}

def get_lingua_labels(lst):
    """
    Принимает список вероятных языков, сортирует в определенном выше порядке и объединяет в одну строку (см. cld2__sentence_level)
    """
    res = []
    for l in lst:
        # print(l.language.name)
        if lang_dict.get(l.language.name):
            res.append(lang_dict[l.language.name])
        else:
            res.append('unk')

    if not res:
        res = ['unk']
    return '-'.join(sort_labels(set(res)))

In [ ]:
df_langproba = pd.DataFrame(index=exprmnt.df.index)

df_langproba[f'{METHOD}__res'] = pd.Series(detector.compute_language_confidence_values_in_parallel(exprmnt.df['text']))
df_langproba[[f'{METHOD}__best_lang', f'{METHOD}__probas']] = df_langproba[f'{METHOD}__res'].apply(lingua__sentence_level).apply(pd.Series)
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    'KAZAKH': f'{METHOD}__kaz',
    'RUSSIAN': f'{METHOD}__rus',
}, inplace=True)

df_langproba[f'{METHOD}__langs'] = pd.Series(detector.detect_multiple_languages_in_parallel_of(exprmnt.df['text'])) # участки текста, размеченные по языкам
df_langproba[f'{METHOD}__all_langs'] = df_langproba[f'{METHOD}__langs'].apply(get_lingua_labels)

In [ ]:
df_langproba[f'{METHOD}__best_lang'].value_counts()/len(df_langproba)

lingua__best_lang
RUSSIAN       0.596247
KAZAKH        0.388597
MONGOLIAN     0.004021
UKRAINIAN     0.003918
BULGARIAN     0.002681
MACEDONIAN    0.001547
SERBIAN       0.001031
BELARUSIAN    0.001031
ENGLISH       0.000412
SOMALI        0.000103
SWAHILI       0.000103
GERMAN        0.000103
TAGALOG       0.000103
SPANISH       0.000103
Name: count, dtype: float64

In [ ]:
df_langproba[f'{METHOD}__all_langs'].value_counts()

lingua__all_langs
kz           3196
ru           2732
ru-unk       2529
unk           339
kz-ru         326
kz-unk        316
kz-ru-unk     261
Name: count, dtype: int64

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=[f'{METHOD}__probas', f'{METHOD}__res'])

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
df = exprmnt.df

### MediaPipe (Language deteciton)

https://ai.google.dev/edge/mediapipe/solutions/text/language_detector


архитектура: https://storage.googleapis.com/mediapipe-assets/LanguageDetector%20Model%20Card.pdf

#### Обработка

In [ ]:
!pip install -q mediapipe

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 82.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.8/135.8 kB 9.3 MB/s eta 0:00:00

In [ ]:
!wget -O detector.tflite -q https://storage.googleapis.com/mediapipe-models/language_detector/language_detector/float32/latest/language_detector.tflite

In [ ]:
import pandas as pd

METHOD = 'mediapipe'
exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus,langid__best_lang,langid__kaz,langid__rus,lingua__best_lang,lingua__kaz,lingua__rus,lingua__langs,lingua__all_langs
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0,kk,-6629.133789,-7293.619141,KAZAKH,1.0,0.0,"[(0, 565, 76, KAZAKH)]",kz
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0,kk,-9796.718750,-10485.810547,KAZAKH,1.0,0.0,"[(0, 789, 96, KAZAKH)]",kz
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0,kk,-2515.423340,-2864.809570,KAZAKH,1.0,0.0,"[(0, 237, 30, KAZAKH)]",kz
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0,kk,-3253.132324,-3682.371826,KAZAKH,1.0,0.0,"[(0, 297, 39, KAZAKH)]",kz
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0,kk,-9981.612305,-10986.610352,KAZAKH,1.0,0.0,"[(0, 268, 32, KAZAKH), (268, 287, 2, RUSSIAN),...",kz-ru

In [ ]:
from mediapipe.tasks import python
from mediapipe.tasks.python import text as mptext

In [ ]:
base_options = python.BaseOptions(model_asset_path="detector.tflite")

options = mptext.LanguageDetectorOptions(base_options=base_options, score_threshold=1e-8)
detector = mptext.LanguageDetector.create_from_options(options)

def mediapipe__sentence_level(text, detector):
    """
    Возвращает наиболее вероятный язык и вероятности для kk и ru
    """
    res = detector.detect(text=text)
    dct_all = {l.language_code: l.probability for l in res.detections}

    best_lang = res.detections[0].language_code

    dct = dict()
    for l in ('kk', 'ru'):
        prob = dct_all.get(l)
        if prob:
            dct[l] = prob
    return best_lang, dct

s = 'Білім саласына қатысты сұрақтар бойынша жедел желі нөмірлері. Номера горячей линии по вопросам образования'
mediapipe__sentence_level(text=s, detector=detector)

('kk', {'kk': 0.7249384522438049, 'ru': 0.007838883437216282})

In [ ]:
df_langproba = pd.DataFrame(index=exprmnt.df.index)

df_langproba[[f'{METHOD}__best_lang', f'{METHOD}__probas']] = exprmnt.df['text'].apply(mediapipe__sentence_level, detector=detector).tolist()
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    'kk': f'{METHOD}__kaz',
    'ru': f'{METHOD}__rus',
}, inplace=True)

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=['mediapipe__probas'])

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
df = exprmnt.df

## Fasttext-based

Обязательно сохранить прогресс перед переустановкой numpy!
После перезапуска ядра запустить подготовительные ячейки в самом начале блокнота

In [ ]:
!pip install numpy==1.26.4

Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.6 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 80.1 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
py3langid 0.3.0 requires numpy>=2.0.0; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [ ]:
!pip install fasttext

Collecting fasttext
  Downloading fasttext-0.9.3.tar.gz (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pybind11>=2.2 (from fasttext)
  Using cached pybind11-3.0.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from fasttext) (75.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fasttext) (1.26.4)
Using cached pybind11-3.0.4-py3-none-any.whl (314 kB)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (pyproject.toml) ... done
  Created wheel for fasttext: filename=fasttext-0.9.3-cp312-cp312-linux_x86_64.whl size=4653905 sha256=749ccf2d18079acff1a4abfd4773620abe73dc92ad8475a555817981c042d723
  Stored in directory: /root/.cache/pip/wheels/20/27/95/a7baf1b435f1cbde017cabdf1e9688526d2b0e929255a359c6
Successfully built fasttext
Installing collected packages: pybind11, fasttext
Successfully installed fasttext-0.9.3 pybind11-3.0.4

In [ ]:
df = pd.read_csv(save_to_path)
df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus,langid__best_lang,langid__kaz,langid__rus,lingua__best_lang,lingua__kaz,lingua__rus,lingua__langs,lingua__all_langs,mediapipe__best_lang,mediapipe__kaz,mediapipe__rus
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0,kk,-6629.1340,-7293.6190,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=565,...",kz,kk,0.999208,1.311968e-06
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0,kk,-9796.7190,-10485.8110,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=789,...",kz,kk,0.998663,1.822960e-06
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0,kk,-2515.4233,-2864.8096,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=237,...",kz,kk,0.999861,1.862460e-08
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0,kk,-3253.1323,-3682.3718,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=297,...",kz,kk,0.999542,3.649036e-08
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0,kk,-9981.6120,-10986.6100,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=268,...",kz-ru,kk,0.993801,7.061346e-06

### Fast-langdetect

https://github.com/LlmKira/fast-langdetect

Обертка, ускоряющая работу FastText

#### Обработка

In [ ]:
!pip install fast-langdetect

Requirement already satisfied: fast-langdetect in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: robust-downloader>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fast-langdetect) (0.0.2)
Requirement already satisfied: requests>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from fast-langdetect) (2.32.4)
Requirement already satisfied: fasttext-predict>=0.9.2.4 in /usr/local/lib/python3.12/dist-packages (from fast-langdetect) (0.9.2.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->fast-langdetect) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->fast-langdetect) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->fast-langdetect) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->fast-langdetect) (2026.4.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from robust-downloader>=0.0.2->fast-langdetect) (4.67.3)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from robust-downloader>=0.0.2->fast-langdetect) (6.10.1)

In [ ]:
import pandas as pd

METHOD = 'fast_langdetect'
exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus,langid__best_lang,langid__kaz,langid__rus,lingua__best_lang,lingua__kaz,lingua__rus,lingua__langs,lingua__all_langs,mediapipe__best_lang,mediapipe__kaz,mediapipe__rus
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0,kk,-6629.1340,-7293.6190,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=565,...",kz,kk,0.999208,1.311968e-06
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0,kk,-9796.7190,-10485.8110,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=789,...",kz,kk,0.998663,1.822960e-06
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0,kk,-2515.4233,-2864.8096,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=237,...",kz,kk,0.999861,1.862460e-08
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0,kk,-3253.1323,-3682.3718,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=297,...",kz,kk,0.999542,3.649036e-08
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0,kk,-9981.6120,-10986.6100,KAZAKH,1.0,0.0,"[DetectionResult(start_index=0, end_index=268,...",kz-ru,kk,0.993801,7.061346e-06

In [ ]:
from fast_langdetect import detect, LangDetector, LangDetectConfig

def fast_langdetect__sentence_level(text):
    """
    Модель считает вероятности для всех поддерживаемых языков. Нас интересуют только вероятности для казахского и русского
    """
    res = detect(text, model='auto', k=-1)
    dct_all = {l['lang']: l['score'] for l in res}

    best_lang = res[0]['lang']

    dct = dict()
    for l in ('kk', 'ru'):
        prob = dct_all.get(l)
        if prob:
            dct[l] = prob
    return best_lang, dct

s = 'Білім саласына қатысты сұрақтар бойынша жедел желі нөмірлері. Номера горячей линии по вопросам образования'
fast_langdetect__sentence_level(s)

('kk', {'kk': 0.996268093585968, 'ru': 0.00010874634608626366})

In [ ]:
df_langproba = pd.DataFrame(index=exprmnt.df.index)

df_langproba[[f'{METHOD}__best_lang', f'{METHOD}__probas']] = exprmnt.df['text'].apply(fast_langdetect__sentence_level).tolist()
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    'kk': f'{METHOD}__kaz',
    'ru': f'{METHOD}__rus',
}, inplace=True)

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=[f'{METHOD}__probas'])

In [ ]:
exprmnt.df[f'{METHOD}__best_lang'].value_counts()

fast_langdetect__best_lang
ru     5977
kk     3496
ky      128
uk       33
tt       13
bg       10
mn        7
sah       7
sr        6
ba        5
be        3
en        3
mk        3
krc       2
ce        2
tg        1
cv        1
mhr       1
az        1
Name: count, dtype: int64

In [ ]:
exprmnt.df[[f'{METHOD}__kaz', f'{METHOD}__rus']].describe()

       fast_langdetect__kaz  fast_langdetect__rus
count           9699.000000           9699.000000
mean               0.353513              0.602095
std                0.467808              0.471251
min                0.000000              0.000000
25%                0.000000              0.000171
50%                0.000166              0.975215
75%                0.994589              0.997384
max                1.000000              1.000000

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
df = exprmnt.df

### GlotLID

In [ ]:
import pandas as pd

METHOD = 'glotlid'
exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus,langid__best_lang,...,lingua__kaz,lingua__rus,lingua__langs,lingua__all_langs,mediapipe__best_lang,mediapipe__kaz,mediapipe__rus,fast_langdetect__best_lang,fast_langdetect__kaz,fast_langdetect__rus
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0,kk,...,1.0,0.0,"[DetectionResult(start_index=0, end_index=565,...",kz,kk,0.999208,1.311968e-06,kk,0.998260,0.000022
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0,kk,...,1.0,0.0,"[DetectionResult(start_index=0, end_index=789,...",kz,kk,0.998663,1.822960e-06,kk,0.816011,0.052039
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0,kk,...,1.0,0.0,"[DetectionResult(start_index=0, end_index=237,...",kz,kk,0.999861,1.862460e-08,kk,0.999802,0.000114
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0,kk,...,1.0,0.0,"[DetectionResult(start_index=0, end_index=297,...",kz,kk,0.999542,3.649036e-08,kk,1.000000,0.000000
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0,kk,...,1.0,0.0,"[DetectionResult(start_index=0, end_index=268,...",kz-ru,kk,0.993801,7.061346e-06,kk,0.997506,0.000012

In [ ]:
import fasttext
from huggingface_hub import hf_hub_download

glotlid_model_path = hf_hub_download(repo_id="cis-lmu/glotlid", filename="model.bin")
glotlid_model = fasttext.load_model(glotlid_model_path)
glotlid_model.predict("коррупция и вляние россии болмаганда бари баскаша болар еді", 3)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.bin:   0%|          | 0.00/1.69G [00:00<?, ?B/s]

(('__label__kaz_Cyrl', '__label__rus_Cyrl', '__label__chu_Cyrl'),
 array([0.82945824, 0.12417033, 0.01198109]))

In [ ]:
def glotlid__sentence_level(text, model):
    """
    Модель считает вероятности для всех поддерживаемых языков.
    Функция возвращает наиболее вероятный язык и распределение вероятностей для казахского и русского.
    """
    # res = model.predict(text, k=3)
    labels, probas = model.predict(text,k=100, threshold=1e-8)
    dct_all = dict(zip(labels, probas))

    best_lang = labels[0]

    dct = dict()
    for l in ('__label__kaz_Cyrl', '__label__rus_Cyrl'):
        prob = dct_all.get(l)
        if prob:
            dct[l.replace('__label', 'glotlid')] = prob
    return best_lang, dct

s = 'мүмкін тайный покупатель сияқты шығарсың'
glotlid__sentence_level(text=s, model=glotlid_model)

('__label__kaz_Cyrl',
 {'glotlid__kaz_Cyrl': 0.9982357621192932,
  'glotlid__rus_Cyrl': 1.1178888598806225e-05})

In [ ]:
df_langproba = pd.DataFrame(index=exprmnt.df.index)

df_langproba[[f'{METHOD}__best_lang', f'{METHOD}__probas']] = exprmnt.df['text'].apply(glotlid__sentence_level, model=glotlid_model).tolist()
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    f'{METHOD}__kaz_Cyrl': f'{METHOD}__kaz',
    f'{METHOD}__rus_Cyrl': f'{METHOD}__rus',
}, inplace=True)

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=[f'{METHOD}__probas'])

In [ ]:
exprmnt.df[f'{METHOD}__best_lang'].value_counts()

glotlid__best_lang
__label__rus_Cyrl    5798
__label__kaz_Cyrl    3584
__label__kir_Cyrl     141
__label__nog_Cyrl      24
__label__orv_Cyrl      22
__label__uzn_Cyrl      13
__label__bul_Cyrl      12
__label__ukr_Cyrl      12
__label__sah_Cyrl      11
__label__alt_Cyrl      10
__label__tat_Cyrl      10
__label__kjh_Cyrl       7
__label__bak_Cyrl       6
__label__mhr_Cyrl       5
__label__kaa_Cyrl       5
__label__tyv_Cyrl       4
__label__srp_Cyrl       3
__label__tuk_Cyrl       3
__label__tgk_Cyrl       3
__label__und_Cyrl       2
__label__eng_Latn       2
__label__kpv_Cyrl       2
__label__gag_Cyrl       2
__label__bel_Cyrl       2
__label__khk_Cyrl       2
__label__krc_Cyrl       2
__label__anp_Deva       1
__label__kum_Cyrl       1
__label__abk_Cyrl       1
__label__mbf_Latn       1
__label__chv_Cyrl       1
__label__tuk_Latn       1
__label__mrj_Cyrl       1
__label__hwc_Latn       1
__label__xal_Cyrl       1
__label__mkd_Cyrl       1
__label__mdf_Cyrl       1
__label__rmy_Cyrl       1
Name: count, dtype: int64

In [ ]:
exprmnt.df[[f'{METHOD}__kaz',f'{METHOD}__rus']].describe()

       glotlid__kaz  glotlid__rus
count   9699.000000   9699.000000
mean       0.368423      0.590590
std        0.478481      0.482831
min        0.000000      0.000000
25%        0.000011      0.000000
50%        0.000043      0.989969
75%        0.999994      0.999325
max        1.000010      1.000010

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
df = exprmnt.df

### Fasttext

In [ ]:
METHOD = 'fasttext'
exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus,langid__best_lang,...,lingua__all_langs,mediapipe__best_lang,mediapipe__kaz,mediapipe__rus,fast_langdetect__best_lang,fast_langdetect__kaz,fast_langdetect__rus,glotlid__best_lang,glotlid__kaz,glotlid__rus
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0,kk,...,kz,kk,0.999208,1.311968e-06,kk,0.998260,0.000022,__label__kaz_Cyrl,0.999986,0.0
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0,kk,...,kz,kk,0.998663,1.822960e-06,kk,0.816011,0.052039,__label__kaz_Cyrl,0.999995,0.0
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0,kk,...,kz,kk,0.999861,1.862460e-08,kk,0.999802,0.000114,__label__kaz_Cyrl,1.000010,0.0
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0,kk,...,kz,kk,0.999542,3.649036e-08,kk,1.000000,0.000000,__label__kaz_Cyrl,1.000009,0.0
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0,kk,...,kz-ru,kk,0.993801,7.061346e-06,kk,0.997506,0.000012,__label__kaz_Cyrl,1.000001,0.0

In [ ]:
import fasttext
from huggingface_hub import hf_hub_download

fasttext_model_path = hf_hub_download(repo_id="facebook/fasttext-language-identification", filename="model.bin")
fasttext_model = fasttext.load_model(fasttext_model_path)
fasttext_model.predict("коррупция и вляние россии болмаганда бари баскаша болар еді", 3)

model.bin:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

(('__label__kaz_Cyrl', '__label__ukr_Cyrl', '__label__tat_Cyrl'),
 array([0.79145634, 0.14584348, 0.02999006]))

In [ ]:
def fasttext__sentence_level(text, model):
    """
    Модель считает вероятности для всех поддерживаемых языков.
    Функция возвращает наиболее вероятный язык и распределение вероятностей для казахского и русского.
    """
    # res = model.predict(text, k=3)
    labels, probas = model.predict(text,k=-1)
    dct_all = dict(zip(labels, probas))

    best_lang = labels[0]

    dct = dict()
    for l in ('__label__kaz_Cyrl', '__label__rus_Cyrl'):
        prob = dct_all.get(l)
        if prob:
            dct[l.replace('__label', 'fasttext')] = prob
    return best_lang, dct

s = 'мүмкін тайный покупатель сияқты шығарсың'
fasttext__sentence_level(text=s, model=fasttext_model)

('__label__kaz_Cyrl',
 {'fasttext__kaz_Cyrl': 1.000008463859558,
  'fasttext__rus_Cyrl': 1.0069999007100705e-05})

In [ ]:
df_langproba = pd.DataFrame(index=exprmnt.df.index)

df_langproba[[f'{METHOD}__best_lang', f'{METHOD}__probas']] = exprmnt.df['text'].apply(fasttext__sentence_level, model=fasttext_model).tolist()
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    f'{METHOD}__kaz_Cyrl': f'{METHOD}__kaz',
    f'{METHOD}__rus_Cyrl': f'{METHOD}__rus',
}, inplace=True)

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=[f'{METHOD}__probas'])

In [ ]:
exprmnt.df[f'{METHOD}__best_lang'].value_counts()

fasttext__best_lang
__label__rus_Cyrl    5778
__label__kaz_Cyrl    3633
__label__kir_Cyrl     140
__label__ukr_Cyrl      35
__label__tat_Cyrl      17
__label__yue_Hant      10
__label__che_Cyrl       9
__label__tgk_Cyrl       7
__label__bul_Cyrl       7
__label__bel_Cyrl       6
__label__kor_Hang       5
__label__chv_Cyrl       5
__label__krc_Cyrl       5
__label__bak_Cyrl       5
__label__srp_Cyrl       4
__label__ady_Cyrl       4
__label__eng_Latn       3
__label__bxr_Cyrl       3
__label__khk_Cyrl       2
__label__vie_Latn       2
__label__zho_Hans       2
__label__oss_Cyrl       2
__label__mkd_Cyrl       2
__label__alt_Cyrl       2
__label__deu_Latn       2
__label__udm_Cyrl       1
__label__pap_Latn       1
__label__san_Deva       1
__label__por_Latn       1
__label__lvs_Latn       1
__label__scn_Latn       1
__label__fra_Latn       1
__label__tuk_Latn       1
__label__twi_Latn       1
Name: count, dtype: int64

In [ ]:
exprmnt.df[[f'{METHOD}__kaz',f'{METHOD}__rus']].describe()

       fasttext__kaz  fasttext__rus
count    9699.000000    9699.000000
mean        0.374173       0.583141
std         0.479793       0.479172
min         0.000010       0.000010
25%         0.000024       0.000010
50%         0.000225       0.972691
75%         1.000010       0.996376
max         1.000010       1.000010

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
df = exprmnt.df

## Словарный метод

Словарный метод, опирающийся на множество источников:
- спелл-чекер hunspell
- толковый словарь казахского языка
- списки суффиксов казахского языка, составленные на основе онлайн-учебника

In [ ]:
METHOD = 'dict'
exprmnt = Experiment(df=df, method=METHOD)
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus,langid__best_lang,...,fast_langdetect__kaz,fast_langdetect__rus,glotlid__best_lang,glotlid__kaz,glotlid__rus,fasttext__best_lang,fasttext__kaz,fasttext__rus,tokens,spans
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0,kk,...,0.998260,0.000022,__label__kaz_Cyrl,0.999986,0.0,__label__kaz_Cyrl,1.00001,0.00001,"[Сандж, тәуелсіз, зерттеу, орталығының, хабарл...","[(1, 6), (8, 16), (17, 24), (25, 36), (37, 49)..."
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0,kk,...,0.816011,0.052039,__label__kaz_Cyrl,0.999995,0.0,__label__kaz_Cyrl,1.00001,0.00001,"[Заңгер, Алексей, Сонның, консультациясына, мы...","[(0, 6), (7, 14), (15, 21), (22, 38), (39, 43)..."
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0,kk,...,0.999802,0.000114,__label__kaz_Cyrl,1.000010,0.0,__label__kaz_Cyrl,1.00001,0.00001,"[Шымкентте, елуге, жуық, әйел, әкімдік, алдына...","[(0, 9), (10, 15), (16, 20), (21, 25), (26, 33..."
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0,kk,...,1.000000,0.000000,__label__kaz_Cyrl,1.000009,0.0,__label__kaz_Cyrl,1.00001,0.00001,"[Өте, маңызды, жобаға, сұхбат, кейіпкері, реті...","[(0, 3), (4, 11), (12, 18), (19, 25), (26, 35)..."
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0,kk,...,0.997506,0.000012,__label__kaz_Cyrl,1.000001,0.0,__label__kaz_Cyrl,1.00001,0.00001,"[Айсұлтанның, құпиясы, Британиялық, Financial,...","[(0, 11), (13, 20), (22, 33), (34, 43), (44, 4..."

#### Сбор словарей

In [ ]:
# скачиваем словари для казахского
!wget https://raw.githubusercontent.com/taem/aspell-kk/refs/heads/master/words

!wget https://raw.githubusercontent.com/kergalym/myspell-kk/refs/heads/upstream/kk_KZ.dic
!wget https://raw.githubusercontent.com/kergalym/myspell-kk/refs/heads/upstream/kk_KZ.aff
!wget https://raw.githubusercontent.com/kergalym/myspell-kk/refs/heads/upstream/kk_noun_adj.aff
!wget https://raw.githubusercontent.com/kergalym/myspell-kk/refs/heads/upstream/kk_noun_adj.dic

--2026-05-14 22:44:12--  https://raw.githubusercontent.com/taem/aspell-kk/refs/heads/master/words
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 867799 (847K) [text/plain]
Saving to: ‘words’

words               100%[===================>] 847.46K  --.-KB/s    in 0.05s

2026-05-14 22:44:12 (15.5 MB/s) - ‘words’ saved [867799/867799]

--2026-05-14 22:44:12--  https://raw.githubusercontent.com/kergalym/myspell-kk/refs/heads/upstream/kk_KZ.dic
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2130055 (2.0M) [text/plain]
Saving to: ‘kk_KZ.dic’

kk_KZ.dic           100%[===================>]   2.03M  --.-KB/s    in 0.07s

2026-05-14 22:44:12 (28.3 MB/s) - ‘kk_KZ.dic’ saved [2130055/2130055]

--2026-05-14 22:44:12--  https://raw.githubusercontent.com/kergalym/myspell-kk/refs/heads/upstream/kk_KZ.aff
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 103192 (101K) [text/plain]
Saving to: ‘kk_KZ.aff’

kk_KZ.aff           100%[===================>] 100.77K  --.-KB/s    in 0.02s

2026-05-14 22:44:13 (6.52 MB/s) - ‘kk_KZ.aff’ saved [103192/103192]

--2026-05-14 22:44:13--  https://raw.githubusercontent.com/kergalym/myspell-kk/refs/heads/upstream/kk_noun_adj.aff
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16430 (16K) [text/plain]
Saving to: ‘kk_noun_adj.aff’

kk_noun_adj.aff     100%[===================>]  16.04K  --.-KB/s    in 0.001s

2026-05-14 22:44:13 (16.8 MB/s) - ‘kk_noun_adj.aff’ saved [16430/16430]

--2026-05-14 22:44:13--  https://raw.githubusercontent.com/kergalym/myspell-kk/refs/heads/upstream/kk_noun_adj.dic
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 378258 (369K) [text/plain]
Saving to: ‘kk_noun_adj.dic’

kk_noun_adj.dic     100%[===================>] 369.39K  --.-KB/s    in 0.03s

2026-05-14 22:44:13 (10.8 MB/s) - ‘kk_noun_adj.dic’ saved [378258/378258]

In [ ]:
# словари
with open('kk_KZ.dic', 'r', encoding='utf8') as f:
    kaz_dict1 = list(f.read().lower().splitlines())
    kaz_dict1 = list(map(lambda x: x[:x.find('/')], kaz_dict1))
    print(len(kaz_dict1))
# 54064

with open('kk_noun_adj.dic', 'r', encoding='utf8') as f:
    kaz_dict2 = list(f.read().lower().splitlines())
    kaz_dict2 = list(map(lambda x: x[:x.find('/')], kaz_dict2))
    print(len(kaz_dict2))
# 20854

with open('words', 'r', encoding='utf8') as f:
    kaz_dict3 = list(f.read().lower().splitlines())
    print(len(kaz_dict3))
# 53717

# толковый словарь казахского языка (не опубликован)
big_kz_dict_path = 'big_kz_dict.txt'
with open(big_kz_dict_path, 'r', encoding='utf8') as f:
    kaz_dict4 = list(f.read().lower().splitlines())
    print(len(kaz_dict4))
# 76006

54064
20854
53717
76006

In [ ]:
# объединенный словарь
kaz_dict = set(kaz_dict1 + kaz_dict2 + kaz_dict3 + kaz_dict4)
print(len(kaz_dict))
# 64840

107943

In [ ]:
# устанавливаем спеллчекер
!sudo apt-get update
!sudo apt-get install libhunspell-dev python3-dev
!pip install hunspell

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,915 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,295 kB]
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.2 MB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,602 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,341 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,286 kB]
Get:16 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,008 kB]
Fetched 32.0 MB in 4s (8,320 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  dictionaries-common hunspell-en-us javascript-common libhunspell-1.7-0
  libjs-sphinxdoc libjs-underscore libtext-iconv-perl python3.10-dev
Suggested packages:
  ispell | aspell | hunspell wordlist hunspell openoffice.org-hunspell
  | openoffice.org-core apache2 | lighttpd | httpd
The following NEW packages will be installed:
  dictionaries-common hunspell-en-us javascript-common libhunspell-1.7-0
  libhunspell-dev libjs-sphinxdoc libjs-underscore libtext-iconv-perl
  python3-dev python3.10-dev
0 upgraded, 10 newly installed, 0 to remove and 7 not upgraded.
Need to get 1,692 kB of archives.
After this operation, 4,388 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtext-iconv-perl amd64 1.7-7build3 [14.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 dictionaries-common all 1.28.14 [185 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 hunspell-en-us all 1:2020.12.07-2 [280 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 javascript-common all 11+nmu1 [5,936 B]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhunspell-1.7-0 amd64 1.7.0-4build1 [175 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhunspell-dev amd64 1.7.0-4build1 [241 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjs-underscore all 1.13.2~dfsg-2 [118 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjs-sphinxdoc all 4.3.2-1 [139 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-dev amd64 3.10.12-1~22.04.15 [508 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-dev amd64 3.10.6-1~22.04.1 [26.0 kB]
Fetched 1,692 kB in 0s (9,803 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 10.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libtext-iconv-perl.
(Reading database ... 118366 files and directories currently installed.)
Preparing to unpack .../0-libtext-iconv-perl_1.7-7build3_amd64.deb ...
Unpacking libtext-iconv-perl (1.7-7build3) ...
Selecting previously unselected package dictionaries-common.
Preparing to unpack .../1-dictionaries-common_1.28.14_all.deb ...
Adding 'diversion of /usr/share/dict/words to /usr/share/dict/words.pre-dictionaries-common by dictionaries-common'
Unpacking dictionaries-common (1.28.14) ...
Selecting previously unselected package hunspell-en-us.
Preparing to unpack .../2-hunspell-en-us_1%3a2020.12.07-2_all.deb ...
Unpacking hunspell-en-us (1:2020.12.07-2) ...
Selecting previously unselected package javascript-common.
Preparing to unpack .../3-javascript-common_11+nmu1_all.deb ...
Unpacking javascript-common (11+nmu1) ...
Selecting previously unselected package libhunspell-1.7-0:amd64.
Preparing to unpack .../4-libhunspell-1.7-0_1.7.0-4build1_amd64.deb ...
Unpacking libhunspell-1.7-0:amd64 (1.7.0-4build1) ...
Selecting previously unselected package libhunspell-dev:amd64.
Preparing to unpack .../5-libhunspell-dev_1.7.0-4build1_amd64.deb ...
Unpacking libhunspell-dev:amd64 (1.7.0-4build1) ...
Selecting previously unselected package libjs-underscore.
Preparing to unpack .../6-libjs-underscore_1.13.2~dfsg-2_all.deb ...
Unpacking libjs-underscore (1.13.2~dfsg-2) ...
Selecting previously unselected package libjs-sphinxdoc.
Preparing to unpack .../7-libjs-sphinxdoc_4.3.2-1_all.deb ...
Unpacking libjs-sphinxdoc (4.3.2-1) ...
Selecting previously unselected package python3.10-dev.
Preparing to unpack .../8-python3.10-dev_3.10.12-1~22.04.15_amd64.deb ...
Unpacking python3.10-dev (3.10.12-1~22.04.15) ...
Selecting previously unselected package python3-dev.
Preparing to unpack .../9-python3-dev_3.10.6-1~22.04.1_amd64.deb ...
Unpacking python3-dev (3.10.6-1~22.04.1) ...
Setting up libtext-iconv-perl (1.7-7build3) ...
Setting up javascript-common (11+nmu1) ...
Setting up dictionaries-common (1.28.14) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Setting up python3.10-dev (3.10.12-1~22.04.15) ...
Setting up hunspell-en-us (1:2020.12.07-2) ...
Setting up libhunspell-1.7-0:amd64 (1.7.0-4build1) ...
Setting up libhunspell-dev:amd64 (1.7.0-4build1) ...
Setting up libjs-underscore (1.13.2~dfsg-2) ...
Setting up libjs-sphinxdoc (4.3.2-1) ...
Setting up python3-dev (3.10.6-1~22.04.1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

Processing triggers for dictionaries-common (1.28.14) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Collecting hunspell
  Downloading hunspell-0.5.5.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: hunspell
  Building wheel for hunspell (setup.py) ... done
  Created wheel for hunspell: filename=hunspell-0.5.5-cp312-cp312-linux_x86_64.whl size=66949 sha256=6ae41c160f5314db6f6503e10412974c6dc1f9a863ab3e63cb02b68a794ed13f
  Stored in directory: /root/.cache/pip/wheels/a4/1e/1c/3438c8e5af66b88b3bab7d99b7c2ec24a9bfe669b57c3f87a6
Successfully built hunspell
Installing collected packages: hunspell
Successfully installed hunspell-0.5.5

In [ ]:
# объединяем словари для спеллчекера
!echo "$(wc -l < kk_KZ.dic) $(wc -l < kk_noun_adj.dic) $(($(wc -l < kk_KZ.dic) + $(wc -l < kk_noun_adj.dic)))" > merged_dics.dic
!grep -v '^$' kk_KZ.dic >> merged_dics.dic
!grep -v '^$' kk_noun_adj.dic >> merged_dics.dic

!cp kk_KZ.aff merged_dics.aff

In [ ]:
import hunspell

kz_spellcheck = hunspell.HunSpell('merged_dics.dic', 'merged_dics.aff')

correct_word = 'қазақстанға'.encode('utf-8')
incorrect_word = 'бир'.encode('utf-8')

# Check words
print(f'Is {correct_word.decode()} spelled correctly?', kz_spellcheck.spell(correct_word))
print(f'Is {incorrect_word.decode()} spelled correctly?', kz_spellcheck.spell(incorrect_word))

# Suggestions
print('Correct options:', kz_spellcheck.suggest(incorrect_word))

# Stemming (analyze)
res = kz_spellcheck.analyze(correct_word)
print(f'Word  {correct_word.decode()} normalized:', res[0].decode())

Is қазақстанға spelled correctly? True
Is бир spelled correctly? False
Correct options: ['би', 'обир', 'бәр', 'биі', 'бір', 'биң', 'бүр', 'бұр', 'бор', 'бар', 'бит', 'тир', 'бие', 'бер', 'бис']
Word  қазақстанға normalized:  st:қазақстан fl:H

In [ ]:
# скачиваем словари для русского спелл-чекера
!wget -O ru_RU.dic https://raw.githubusercontent.com/wooorm/dictionaries/refs/heads/main/dictionaries/ru/index.dic
!wget -O ru_RU.aff https://raw.githubusercontent.com/wooorm/dictionaries/refs/heads/main/dictionaries/ru/index.aff

--2026-05-14 22:46:18--  https://raw.githubusercontent.com/wooorm/dictionaries/refs/heads/main/dictionaries/ru/index.dic
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3473191 (3.3M) [text/plain]
Saving to: ‘ru_RU.dic’

ru_RU.dic           100%[===================>]   3.31M  --.-KB/s    in 0.1s

2026-05-14 22:46:18 (33.5 MB/s) - ‘ru_RU.dic’ saved [3473191/3473191]

--2026-05-14 22:46:18--  https://raw.githubusercontent.com/wooorm/dictionaries/refs/heads/main/dictionaries/ru/index.aff
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 71236 (70K) [text/plain]
Saving to: ‘ru_RU.aff’

ru_RU.aff           100%[===================>]  69.57K  --.-KB/s    in 0.01s

2026-05-14 22:46:18 (5.50 MB/s) - ‘ru_RU.aff’ saved [71236/71236]

In [ ]:
ru_spellcheck = hunspell.HunSpell('ru_RU.dic', 'ru_RU.aff')

correct_word = 'остановленного'.encode('utf-8')
incorrect_word = 'остоновочный'.encode('utf-8')

# Check words
print(f'Is {correct_word.decode()} spelled correctly?', ru_spellcheck.spell(correct_word))
print(f'Is {incorrect_word.decode()} spelled correctly?', ru_spellcheck.spell(incorrect_word))

# Suggestions
print('Correct options:', ru_spellcheck.suggest(incorrect_word))

# Stemming (analyze)
res = ru_spellcheck.analyze(correct_word)
print(f'Word  {correct_word.decode()} normalized:', res[0].decode()) # res[0].decode().split()[0].split(':')[1]

Is остановленного spelled correctly? True
Is остоновочный spelled correctly? False
Correct options: ['остановочный', 'обстановочный', 'установочный', 'водосточный', 'стыковочный']
Word  остановленного normalized:  st:остановленный fl:A

#### Обработка

Проверка русских слов осуществляется в один этап -- с помощью spellchecker'а: если spellchecker подтверждает правильное написание слова, то слово существует в русском языке.

В силу сложной системы словоизменения в казахском языке проверка состоит из нескольких этапов:
1) проверка с помощью spellchecker'а
2) проверка в толковом словаре (на всякий случай)
3) итеративно убираем аффиксы с конца слова; сортируем каждую группу аффиксов по убыванию длины суффикса и сравниваем, оканчивается ли слово на этот суффикс; если оканчивается -- убираем его с конца слова и повторяем шаги 1) и 2) пока либо "обрезанное" слово не найдется в словаре или спелл-чекере, либо не останется морфем, которые можно удалить с конца

In [ ]:
import re
from string import punctuation

cyr_alph = 'АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя'
lat_alph = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz'
special_char = 'ӘәҒғҚқҢңӨөҰұҮүҺһІі'
alph = ''.join(set(list(cyr_alph + special_char + lat_alph)))

table = str.maketrans({
    'ə':'ә', # 601 -> 1241
    'Ə':'Ә', # 399 -> 1240
    'I':'І', # 73 -> 1030
    'i':'і' # 105 -> 1110
})

def normalize_special_chars(word):
    """
    Корректирует специализированные символы в казахских словах
    """
    return word.translate(table)

def extract_words(text, include_nonwords=True):
    """
    Извлекает из текста отдельные слова
    """
    text = re.sub(r'\\n', ' '*3, text)
    patt = f'[{alph}]+'

    tokens = []
    spans = []

    res = re.finditer(patt, text)
    for m in res:
        tokens.append(m.group())
        spans.append((m.start(0), m.end(0)))

    return tokens, spans

In [ ]:
df[['tokens', 'spans']] = df['text'].str.strip().apply(extract_words).apply(pd.Series)

In [ ]:
# noun_aff: [plural] [ы|і] [poss] [case] [adj] # https://aclanthology.org/W10-4124.pdf
noun_plural = ['лар', 'лер', 'дар', 'дер', 'тар', 'тер']
# noun_poss = ['ым', 'ім', 'м', 'ымыз', 'іміз', 'мыз', 'міз', 'ың', 'ің', 'ң', 'ыңыз', 'іңіз', 'ңыз', 'ңіз', 'сы', 'сі', 'ы', 'і']
noun_poss = ['м', 'мыз', 'міз', 'ң', 'ңыз', 'ңіз', 'сы', 'сі']
noun_case = ['дан', 'ден', 'тан', 'тен', 'нан', 'нен', 'да', 'де', 'та', 'те', 'нда', 'нде', 'ға', 'ге', 'қа', 'ке', 'на', 'не', 'а', 'е', 'дың', 'дің', 'тың', 'тің', 'ның', 'нің', 'ды', 'ді', 'ты', 'ті', 'ны', 'ні', 'н', 'бен', 'пен', 'мен']
noun_adj = ['ды', 'ді', 'ты', 'ті', 'лы', 'лі', 'сыз', 'сіз', 'ғы', 'гі', 'қы', 'кі', 'дай', 'дей', 'тай', 'тей', 'ндай', 'ндей', 'и', 'ы', 'дық', 'дік', 'тық', 'тік', 'лық', 'лік', 'паз', 'тал', 'ғыш', 'гіш', 'қыш', 'кіш', 'шек', 'шақ', 'шыл', 'шіл']

# verb_aff: ("ы"|"і") [voice] [neg] ["й"] [у] pers_{1,2} ["а"|"е"|"й"] tense [infl] [а|е|ы|и] [mood] [] # https://kaz-tili.kz/glag.htm
verb_voice = [
    'н', # возвр, страд
    'л', # страд
    'с', # совм
    'т', 'з', 'р', 'дыр', 'дір', 'тыр', 'тір', 'ғыз', 'гіз', 'қыз', 'кіз' # понуд
]
verb_neg = [
    'ба', 'бе', 'бы', 'бі',
    'па', 'пе', 'пы', 'пі',
    'ма', 'ме', 'мы', 'мі'
]
pers_1 = [
    'мын', 'мін', 'пын', 'пін', 'бын', 'бін',
    'мыз', 'міз', 'пыз', 'піз', 'быз', 'біз',
    'сың', 'сің',
    'сыңдар', 'сіңдер',
    'сыз', 'сіз',
    'сыздар', 'сіздер',
    'ды', 'ді', 'ты', 'ті'
]
pers_2 = [
    'м',
    'қ', 'к',
    'ң', 'ңдар', 'ңдер',
    'ңыз', 'ңіз',
    'ңыздар', 'ңіздер'
]

verb_pers = pers_1 + pers_2

verb_tense = [
    'уш', 'уші', # причастие наст. времени #ушы
    'ып', 'іп', 'п', # наст, давнопрош. неочев
    'д', 'ді', 'т', 'ті', # прошед #ды, ты
    'а', 'е', 'й', # переходн
    'са', 'се', # усл
    'ар', 'ер', 'р', # буд. предпол
    'бақ', 'бек', 'пақ', 'пек', 'мақ', 'мек', # буд. намер
    'ған', 'ген', 'қан', 'кен', # давнопрош. очев
    'атын', 'етін', 'йтын', 'йтін', # перех прош
    'ғал', 'гелі', 'қал', 'келі' # дееприч цели # ғалы, қалы
]
# verb_infl = ['ған', 'ген', 'қан', 'кен']
verb_mood_imper = [
    'йын', 'йін',
    'йық', 'йік',
    'ңдар', 'ңдер',
    'ңыз', 'ңіз',
    'ңыздар' ,'ңіздер',
    'сын', 'сін'
]
verb_mood_wish = [
    'ғы', 'гі', 'қы', 'кі'
]

verb_mood = verb_mood_imper + verb_mood_wish

In [ ]:
from collections import Counter
import re

def trim_affix(word, aff_list):
    # print(word)
    for aff in sorted(aff_list, key=lambda x: len(x))[::-1]:
        if word.endswith(aff):
            # print(word, aff)
            word = word[:-len(aff)]
            # print(word)
            return word
    return word

def stem_word(word):
    pos = [
        # verb
        # ("ы"|"i") [voice] [neg] [у] ["й"] pers_{1,2} ["а"|"е"|"й"] tense [infl] [а|е|ы|и] [mood]
        [verb_mood, ['а', 'е', 'ы', 'и'], verb_tense, ['а', 'е', 'й'], verb_pers, ['й'], ['у'], verb_neg, verb_voice, ['ы', 'і']],
        # noun
        # [plural] [ы|i] [poss] [case]
        [noun_adj, noun_case, noun_poss, ['ы', 'і'], noun_plural]
    ]

    for pos_seq in pos:
        for aff_lst in pos_seq:
            word = trim_affix(word, aff_lst)
            print(word)
    return word


def check_kaz(word_init):
    """
    Проверить слово или его производные в казахских словарях
    """

    def simple_lookup(t):
        return re.search(f'[{special_char}]', t) or kz_spellcheck.spell(t.title().encode('utf-8')) or t in kaz_dict # any(ch in 'ӘәҒғҚқҢңӨөҰұҮүҺһІі' for ch in t) or

    if simple_lookup(word_init):
        return True

    # если полное слово не нейдено в словаре, делаем стемминг
    pos = [
        # verb
        # ("ы"|"i") [voice] [neg] [у] ["й"] pers_{1,2} ["а"|"е"|"й"] tense [infl] [а|е|ы|и] [mood]
        [verb_mood, ['а', 'е', 'ы', 'и'], verb_tense, ['а', 'е', 'й'], verb_pers, ['й'], ['у'], verb_neg, verb_voice, ['ы', 'і']],
        # noun
        # [plural] [ы|i] [poss] [case]
        [noun_adj, noun_case, noun_poss, ['ы', 'і'], noun_plural]
    ]

    for pos_seq in pos:
        word = word_init
        for aff_lst in pos_seq:
            word = trim_affix(word, aff_lst)
            # print(word)
            if simple_lookup(word):
                return True
            # print(word)
    return False

def check_rus(word):
    """
    Проверить слово в русских словарях
    """
    return ru_spellcheck.spell(word.title().encode('utf-8')) # or word in rus_dict

def dict__sentence_level(tokens):
    """
    Проверяет каждое слово на наличие в казахском и русском языках. Если слово нашлось в обоих -- указывается тег ambig, если ни в одном -- то unk.

    Функция возвращает
    - язык, к которому принадлежит наибольшая доля слов
    - для каждого языка -- какая доля слов на этом языке используется в предложении
    - слово с указанием его порядкового номера и тег
    """

    c = Counter() # счетчик: сколько слов на каком языке
    res = {}

    for i, t in enumerate(tokens):
        lang = 'unk'

        if found.get(t):
            lang = found[t]

        else:
            if check_kaz(t):
                lang = 'kz'

            if check_rus(t):
                if lang=='unk':
                    lang = 'ru'
                else:
                    lang = 'ambig'

            found[t] = lang
        c.update([lang])

        res[f'{i}_{t}'] = lang

    perc = {x[0]: x[1]/c.total() for x in c.items()}

    # сортируем так, чтобы при равных вероятностях в качестве best_lang был 'kz' или'ru'
    dt = list(filter(lambda x: x[1] == c.most_common(1)[0][1] and x[0] in ('kz', 'ru'), list(c.most_common())))
    if dt:
        best_lang = dt[0][0]
    else:
        best_lang = c.most_common(1)[0][0]
    return best_lang, perc, res

In [ ]:
df_langproba = pd.DataFrame(index=exprmnt.df.index)

found = dict() # кэш
df_langproba['n_tokens'] = exprmnt.df['tokens'].apply(len)
df_langproba[[f'{METHOD}__best_lang', f'{METHOD}__probas', f'{METHOD}__token_annot']] = exprmnt.df['tokens'].apply(dict__sentence_level).tolist()
df_langproba = pd.concat([df_langproba, df_langproba[f'{METHOD}__probas'].apply(pd.Series)], axis=1)
df_langproba.rename(columns={
    'kz': f'{METHOD}__kaz',
    'ru': f'{METHOD}__rus',
    'ambig': f'{METHOD}__ambig',
    'unk': f'{METHOD}__unk'
}, inplace=True)

In [ ]:
print(*df_langproba['dict__token_annot'].to_list()[:10], sep='\n'+'='*80+'\n')

{'0_Сандж': 'unk', '1_тәуелсіз': 'kz', '2_зерттеу': 'kz', '3_орталығының': 'kz', '4_хабарлауынша': 'unk', '5_елімізде': 'kz', '6_коронавирус': 'kz', '7_жұқтырған': 'kz', '8_адам': 'ambig', '9_саны': 'ambig', '10_миллион': 'ambig', '11_адамға': 'kz', '12_жеткен': 'kz', '13_ал': 'kz', '14_ресми': 'kz', '15_дерек': 'kz', '16_бұдан': 'kz', '17_жүз': 'kz', '18_есе': 'kz', '19_аз': 'ambig', '20_Десек': 'kz', '21_те': 'ambig', '22_Тоқаев': 'kz', '23_коронавирусқа': 'kz', '24_қарсы': 'kz', '25_кезекті': 'kz', '26_жиын': 'kz', '27_өткізіп': 'kz', '28_жағдайды': 'kz', '29_көктемдегідей': 'kz', '30_жаппай': 'kz', '31_карантинге': 'kz', '32_жеткізбеуді': 'kz', '33_тапсырды': 'kz', '34_Әр': 'kz', '35_өңір': 'kz', '36_бойынша': 'kz', '37_карантин': 'ambig', '38_енгізіле': 'kz', '39_бастады': 'kz', '40_адамдар': 'kz', '41_тағы': 'kz', '42_да': 'ambig', '43_жұмысынан': 'kz', '44_айырылды': 'kz', '45_бірақ': 'kz', '46_теңге': 'kz', '47_төлем': 'kz', '48_осы': 'ambig', '49_жолы': 'kz', '50_болмайтын': 'kz', '51_болды': 'kz', '52_Яғни': 'kz', '53_заң': 'kz', '54_жүзінде': 'kz', '55_локдаун': 'unk', '56_жоқ': 'kz', '57_ал': 'kz', '58_іс': 'kz', '59_жүзінде': 'kz', '60_бар': 'ambig', '61_Біздің': 'kz', '62_биліктің': 'kz', '63_жаңа': 'kz', '64_қулығы': 'kz', '65_қандай': 'kz', '66_Шығарылымда': 'kz', '67_осы': 'ambig', '68_туралы': 'kz', '69_және': 'kz', '70_өңірлердегі': 'kz', '71_жағдай': 'kz', '72_туралы': 'kz', '73_сөз': 'kz', '74_қозғайтын': 'kz', '75_боламыз': 'kz'}
================================================================================
{'0_Заңгер': 'kz', '1_Алексей': 'ru', '2_Сонның': 'kz', '3_консультациясына': 'kz', '4_мына': 'kz', '5_сілтеме': 'kz', '6_арқылы': 'kz', '7_жазыла': 'kz', '8_аласыз': 'kz', '9_Каналға': 'kz', '10_қолдау': 'kz', '11_көрсету': 'kz', '12_kaspi': 'unk', '13_Қазақстанда': 'kz', '14_рұқсат': 'kz', '15_етілген': 'kz', '16_митингіге': 'kz', '17_екі': 'kz', '18_жүз': 'kz', '19_адам': 'ambig', '20_әрең': 'kz', '21_жиналса': 'kz', '22_Беларусь': 'ru', '23_халқы': 'kz', '24_үш': 'kz', '25_айдан': 'kz', '26_бері': 'kz', '27_дамыл': 'kz', '28_таппай': 'kz', '29_күн': 'kz', '30_сайын': 'kz', '31_әділетсіз': 'kz', '32_сайлауға': 'kz', '33_қарсы': 'kz', '34_наразылыққа': 'kz', '35_шығуын': 'kz', '36_жалғастыруда': 'kz', '37_Ал': 'kz', '38_Молдовада': 'unk', '39_президент': 'ambig', '40_сайлауында': 'kz', '41_бұрынғы': 'kz', '42_премьер': 'ambig', '43_министр': 'ambig', '44_оппозициялық': 'kz', '45_партияның': 'kz', '46_төрайымы': 'kz', '47_жеңіске': 'kz', '48_жетті': 'kz', '49_Қазіргі': 'kz', '50_президент': 'ambig', '51_жеңілгенін': 'kz', '52_мойындамады': 'kz', '53_Лукашенконы': 'unk', '54_президент': 'ambig', '55_сайлауында': 'kz', '56_жеңіске': 'kz', '57_жеткенімен': 'kz', '58_құттықтағандардың': 'kz', '59_қатарында': 'kz', '60_ол': 'kz', '61_да': 'ambig', '62_бар': 'ambig', '63_еді': 'kz', '64_Сондай': 'kz', '65_ақ': 'kz', '66_елімізде': 'kz', '67_парламент': 'ambig', '68_сайлауы': 'kz', '69_деп': 'ambig', '70_аталатын': 'kz', '71_театр': 'ambig', '72_қойылымы': 'kz', '73_жалғасуда': 'kz', '74_Ауыл': 'kz', '75_партиясы': 'kz', '76_журналистерден': 'unk', '77_қашып': 'kz', '78_жүр': 'kz', '79_Бүгінгі': 'kz', '80_шығарылымда': 'kz', '81_осы': 'ambig', '82_тақырыптар': 'kz', '83_және': 'kz', '84_Қазақстанда': 'kz', '85_саяси': 'kz', '86_өзгерістер': 'kz', '87_қашан': 'kz', '88_орын': 'kz', '89_алады': 'kz', '90_деген': 'kz', '91_сұрақ': 'kz', '92_аясында': 'kz', '93_сөз': 'kz', '94_қозғайтын': 'kz', '95_боламыз': 'kz'}
================================================================================
{'0_Шымкентте': 'unk', '1_елуге': 'kz', '2_жуық': 'kz', '3_әйел': 'kz', '4_әкімдік': 'kz', '5_алдына': 'kz', '6_жиналды': 'kz', '7_Мұны': 'kz', '8_Азаттық': 'kz', '9_Радиосы': 'kz', '10_хабарлады': 'kz', '11_Азаттықтың': 'kz', '12_жазуынша': 'unk', '13_олардың': 'kz', '14_негізгі': 'kz', '15_талабы': 'kz', '16_әлеуметтік': 'kz', '17_мәселелер': 'kz', '18_Соның': 'kz', '19_ішінде': 'kz', '20_баспана': 'kz', '21_мен': 'kz', '22_жәрдемақы': 'kz', '23_мәселесі': 'kz', '24_Жиналғандар': 'kz', '25_әкімнің': 'kz', '26_шығуын': 'kz', '27_талап': 'kz', '28_етіп': 'kz', '29_тұр': 'kz'}
================================================================================
{'0_Өте': 'kz', '1_маңызды': 'kz', '2_жобаға': 'kz', '3_сұхбат': 'kz', '4_кейіпкері': 'kz', '5_ретінде': 'kz', '6_кішкентайында': 'kz', '7_тұрмыстық': 'kz', '8_зорлық': 'kz', '9_зомбылықтың': 'kz', '10_яғни': 'kz', '11_әкесінің': 'kz', '12_анасын': 'kz', '13_ұрып': 'kz', '14_соққан': 'kz', '15_көріністің': 'kz', '16_куәсі': 'kz', '17_болған': 'kz', '18_ер': 'ambig', '19_адам': 'ambig', '20_үй': 'kz', '21_тиранының': 'kz', '22_ұлы': 'kz', '23_қажет': 'kz', '24_Астанадан': 'kz', '25_табылса': 'kz', '26_жақсы': 'kz', '27_болар': 'kz', '28_еді': 'kz', '29_Бұл': 'kz', '30_іс': 'kz', '31_шұғыл': 'kz', '32_алайда': 'kz', '33_уақыт': 'kz', '34_жағын': 'kz', '35_келісе': 'kz', '36_аламыз': 'kz', '37_Телеграмда': 'unk', '38_жазсаңыз': 'kz', '39_болады': 'kz'}
================================================================================
{'0_Айсұлтанның': 'kz', '1_құпиясы': 'kz', '2_Британиялық': 'kz', '3_Financial': 'unk', '4_times': 'unk', '5_басылымы': 'kz', '6_Назарбаевтың': 'kz', '7_күйеу': 'kz', '8_баласы': 'kz', '9_Тимур': 'ru', '10_Құлыбаев': 'kz', '11_туралы': 'kz', '12_материал': 'ambig', '13_шығарған': 'kz', '14_еді': 'kz', '15_Басылымның': 'kz', '16_мәліметінше': 'kz', '17_Құлыбаев': 'kz', '18_Қытай': 'kz', '19_мен': 'kz', '20_Еуропаны': 'kz', '21_жалғайтын': 'kz', '22_газ': 'ambig', '23_құбыры': 'kz', '24_жобасынан': 'kz', '25_жасырын': 'kz', '26_жолмен': 'kz', '27_шамамен': 'kz', '28_миллион': 'ambig', '29_доллар': 'ambig', '30_пайда': 'kz', '31_көрген': 'kz', '32_Журналист': 'ambig', '33_материал': 'ambig', '34_соңында': 'kz', '35_Айсұлтан': 'kz', '36_Назарбаевқа': 'kz', '37_тоқталады': 'kz', '38_Мақала': 'kz', '39_ішінде': 'kz', '40_сипатталған': 'kz', '41_схеманың': 'kz', '42_жария': 'kz', '43_болуына': 'kz', '44_белгілі': 'kz', '45_бір': 'kz', '46_деңгейде': 'kz', '47_Айсұлтанның': 'kz', '48_түрткі': 'kz', '49_болғаны': 'kz', '50_жазылған': 'kz', '51_Нақтырақ': 'kz', '52_айтқанда': 'kz', '53_отбасының': 'kz', '54_жемқорлық': 'kz', '55_істері': 'kz', '56_туралы': 'kz', '57_мәлімдемесі': 'kz', '58_негіз': 'kz', '59_болған': 'kz', '60_Сондай': 'kz', '61_ақ': 'kz', '62_Айсұлтан': 'kz', '63_Назарбаев': 'kz', '64_кокаинді': 'kz', '65_артық': 'kz', '66_мөлшерде': 'kz', '67_қолданғаннан': 'kz', '68_қайтыс': 'kz', '69_болды': 'kz', '70_делінген': 'kz', '71_Оның': 'kz', '72_денесі': 'kz', '73_жылы': 'kz', '74_тамыз': 'kz', '75_күні': 'kz', '76_Лондондағы': 'kz', '77_Грин': 'ru', '78_парктен': 'kz', '79_табылды': 'kz', '80_Денесін': 'kz', '81_тексергеннен': 'kz', '82_кейін': 'kz', '83_кокаиннен': 'kz', '84_уланғаны': 'kz', '85_анықталды': 'kz', '86_деп': 'ambig', '87_жазды': 'kz', '88_басылым': 'kz', '89_Есіңізде': 'kz', '90_болса': 'kz', '91_бұған': 'kz', '92_дейін': 'kz', '93_көп': 'kz', '94_басылым': 'kz', '95_ресми': 'kz', '96_түрде': 'kz', '97_оның': 'kz', '98_өлімінің': 'kz', '99_себебі': 'kz', '100_жүрегінің': 'kz', '101_тоқтап': 'kz', '102_қалуы': 'kz', '103_деп': 'ambig', '104_хабарланған': 'kz', '105_болатын': 'kz'}
================================================================================
{'0_Астанадағы': 'kz', '1_кибер': 'ru', '2_жаттығу': 'kz', '3_нәтижесі': 'kz', '4_туралы': 'kz', '5_брифинг': 'ambig', '6_өтті': 'kz', '7_Онда': 'kz', '8_Цифрлық': 'kz', '9_даму': 'ambig', '10_министрлігінің': 'kz', '11_өкілі': 'kz', '12_Google': 'unk', '13_дың': 'kz', '14_сертификатты': 'kz', '15_бұғаттауын': 'kz', '16_НАТО': 'unk', '17_ның': 'kz', '18_екіжақты': 'kz', '19_ұстанымы': 'kz', '20_деп': 'ambig', '21_түсіндіруге': 'kz', '22_тырысты': 'kz', '23_Ақпараттық': 'kz', '24_қауіпсіздік': 'kz', '25_комитетінің': 'kz', '26_басшысы': 'kz', '27_Руслан': 'ru', '28_Әбдіқалықовтың': 'kz', '29_айтуынша': 'kz', '30_Батыс': 'kz', '31_біздің': 'kz', '32_арнайы': 'kz', '33_қызметтің': 'kz', '34_тиімді': 'kz', '35_жұмыс': 'kz', '36_істей': 'kz', '37_алмағанын': 'kz', '38_қалайды': 'kz', '39_екен': 'kz', '40_Цитатадан': 'kz', '41_үзінді': 'kz', '42_Бұл': 'kz', '43_елдер': 'kz', '44_НАТО': 'unk', '45_құрамында': 'kz', '46_бар': 'ambig', '47_Назар': 'ambig', '48_аударып': 'kz', '49_қарар': 'kz', '50_болсаңыз': 'kz', '51_оларда': 'kz', '52_не': 'ambig', '53_Facebook': 'unk', '54_пен': 'kz', '55_не': 'ambig', '56_Google': 'unk', '57_мен': 'kz', '58_проблема': 'ambig', '59_жоқ': 'kz', '60_Проблема': 'ambig', '61_біздің': 'kz', '62_елде': 'kz', '63_себебі': 'kz', '64_біз': 'kz', '65_НАТО': 'unk', '66_құрамында': 'kz', '67_емес': 'kz', '68_ҰҚШҰ': 'kz', '69_құрамындамыз': 'kz', '70_Сәйкесінше': 'kz', '71_саяси': 'kz', '72_тұрғыдан': 'kz', '73_ешкім': 'kz', '74_біздің': 'kz', '75_сертификатты': 'kz', '76_мойындамайды': 'kz', '77_Себебі': 'kz', '78_біздің': 'kz', '79_арнайы': 'kz', '80_қызметтің': 'kz', '81_шетелдік': 'kz', '82_қызмет': 'kz', '83_секілді': 'kz', '84_тиімді': 'kz', '85_жұмыс': 'kz', '86_істегенін': 'kz', '87_ешкім': 'kz', '88_қаламайды': 'kz', '89_Өте': 'kz', '90_қарапайым': 'kz', '91_сұрақ': 'kz', '92_Ол': 'kz', '93_механизмдерді': 'kz', '94_біз': 'kz', '95_ойлап': 'kz', '96_тапқан': 'kz', '97_жоқпыз': 'kz', '98_Міне': 'kz', '99_қазақтар': 'kz', '100_өте': 'kz', '101_ақылды': 'kz', '102_алды': 'kz', '103_да': 'ambig', '104_қауіпсіздік': 'kz', '105_сертификатын': 'kz', '106_ойлап': 'kz', '107_тапты': 'kz', '108_Біз': 'kz', '109_басқалар': 'kz', '110_не': 'ambig', '111_істеп': 'kz', '112_жатқанына': 'kz', '113_ғана': 'kz', '114_қарадық': 'kz', '115_Болды': 'kz', '116_Бірақ': 'kz', '117_бізде': 'kz', '118_үнемі': 'kz', '119_осындай': 'kz', '120_екіжақты': 'kz', '121_ұстаным': 'kz', '122_бар': 'ambig', '123_Яғни': 'kz', '124_біреулерге': 'kz', '125_мұны': 'kz', '126_істеуге': 'kz', '127_болады': 'kz', '128_себебі': 'kz', '129_ол': 'kz', '130_дұрыс': 'kz', '131_әрі': 'kz', '132_демократияшыл': 'kz', '133_Ал': 'kz', '134_бір': 'kz', '135_ел': 'ambig', '136_оны': 'kz', '137_істеуге': 'kz', '138_толық': 'kz', '139_құқы': 'kz', '140_барын': 'kz', '141_түсініп': 'kz', '142_өз': 'kz', '143_территориясында': 'kz', '144_істеуге': 'kz', '145_тырысса': 'kz', '146_жоқ': 'kz', '147_бізге': 'kz', '148_неге': 'ambig', '149_екені': 'kz', '150_белгісіз': 'kz', '151_оны': 'kz', '152_істеуге': 'kz', '153_болмайды': 'kz', '154_екен': 'kz'}
================================================================================
{'0_Ағаш': 'kz', '1_кескендерге': 'unk', '2_салынатын': 'kz', '3_айыппұл': 'kz', '4_көлемі': 'kz', '5_өспек': 'kz', '6_Сенаторлар': 'kz', '7_Экология': 'ambig', '8_кодексіне': 'kz', '9_өзгертулер': 'kz', '10_енгізді': 'kz', '11_Ағаштарды': 'kz', '12_заңсыз': 'kz', '13_кескендерге': 'unk', '14_салынатын': 'kz', '15_әкімшілік': 'kz', '16_айыппұл': 'kz', '17_көлемі': 'kz', '18_бес': 'ambig', '19_есеге': 'kz', '20_өседі': 'kz', '21_Жеке': 'kz', '22_тұлғаларға': 'kz', '23_АЕК': 'unk', '24_мың': 'kz', '25_теңге': 'kz', '26_ШОБ': 'unk', '27_АЕК': 'unk', '28_ден': 'kz', '29_АЕК': 'unk', '30_ге': 'kz', '31_дейін': 'kz', '32_мыңнан': 'kz', '33_мыңға': 'kz', '34_дейін': 'kz', '35_ірі': 'kz', '36_кәсіпорындарға': 'kz', '37_АЕК': 'unk', '38_миллион': 'ambig', '39_теңге': 'kz', '40_айыппұл': 'kz', '41_салынады': 'kz', '42_Мұндай': 'kz', '43_құқық': 'kz', '44_бұзушылық': 'kz', '45_қайталанған': 'kz', '46_жағдайда': 'kz', '47_немесе': 'kz', '48_ерекше': 'kz', '49_қорғалатын': 'kz', '50_табиғи': 'kz', '51_аумақтардағы': 'kz', '52_ағаштарды': 'kz', '53_кескені': 'kz', '54_үшін': 'kz', '55_ірі': 'kz', '56_кәсіпорындар': 'kz', '57_АЕК': 'unk', '58_немесе': 'kz', '59_миллион': 'ambig', '60_теңгеге': 'kz', '61_дейін': 'kz', '62_төлейді': 'kz', '63_Сондай': 'kz', '64_ақ': 'kz', '65_келтірілген': 'kz', '66_шығын': 'kz', '67_АЕК': 'unk', '68_ден': 'kz', '69_асып': 'kz', '70_кетсе': 'kz', '71_онда': 'kz', '72_заң': 'kz', '73_бұзушылар': 'kz', '74_қылмыстық': 'kz', '75_жауапкершілікке': 'kz', '76_тартылады': 'kz', '77_Жазаны': 'kz', '78_күшейтіп': 'kz', '79_жатқанымен': 'kz', '80_заң': 'kz', '81_бәріне': 'kz', '82_бірдей': 'kz', '83_жүрмейтін': 'kz', '84_сияқты': 'kz', '85_Мысалы': 'kz', '86_бүгін': 'kz', '87_қылмыс': 'kz', '88_құрамы': 'kz', '89_болмағаны': 'kz', '90_үшін': 'kz', '91_Алматы': 'kz', '92_әкімдігінің': 'kz', '93_жаңа': 'kz', '94_Aport': 'unk', '95_Mall': 'unk', '96_East': 'unk', '97_салынып': 'kz', '98_жатқан': 'kz', '99_аумағындағы': 'kz', '100_мың': 'kz', '101_ағашты': 'kz', '102_кесу': 'kz', '103_туралы': 'kz', '104_талабы': 'kz', '105_қабылданбады': 'kz', '106_Сонда': 'kz', '107_тапсырманы': 'kz', '108_беруші': 'kz', '109_жазаланбай': 'unk', '110_ма': 'kz', '111_Одан': 'kz', '112_бөлек': 'kz', '113_Алматыдағы': 'kz', '114_Sulpak': 'unk', '115_дүкенінің': 'kz', '116_алдындағы': 'kz', '117_ағаштардың': 'kz', '118_кесілуі': 'kz', '119_Дүкен': 'kz', '120_жазадан': 'kz', '121_құтылып': 'kz', '122_кетуі': 'kz', '123_әбден': 'kz', '124_мүмкін': 'kz', '125_Өйткені': 'kz', '126_жалғыз': 'kz', '127_күдікті': 'kz', '128_жұмысты': 'kz', '129_Sulpak': 'unk', '130_тапсырысы': 'kz', '131_бойынша': 'kz', '132_орындаған': 'kz', '133_мердігер': 'kz', '134_Бұл': 'kz', '135_да': 'ambig', '136_көрнекілік': 'kz', '137_үшін': 'kz', '138_қабылданған': 'kz', '139_заң': 'kz', '140_ба': 'kz', '141_Шын': 'kz', '142_мәнінде': 'kz', '143_қоғам': 'kz', '144_дүрлігіп': 'kz', '145_жатқанда': 'kz', '146_нағыз': 'kz', '147_кінәлілер': 'kz', '148_жазадан': 'kz', '149_сытылып': 'kz', '150_шығады': 'kz'}
================================================================================
{'0_Арнаға': 'kz', '1_қолдау': 'kz', '2_көрсету': 'kz', '3_kaspi': 'unk', '4_жыл': 'kz', '5_мен': 'kz', '6_сол': 'kz', '7_жылы': 'kz', '8_болған': 'kz', '9_бар': 'ambig', '10_бәлекеттен': 'kz', '11_құтылғымыз': 'kz', '12_келгені': 'kz', '13_сонша': 'kz', '14_бар': 'ambig', '15_үмітті': 'kz', '16_ге': 'kz', '17_артып': 'kz', '18_қойдық': 'kz', '19_Десе': 'kz', '20_де': 'ambig', '21_өзгергені': 'kz', '22_күнтізбе': 'kz', '23_ғана': 'kz', '24_ал': 'kz', '25_көп': 'kz', '26_нәрсе': 'kz', '27_сол': 'kz', '28_қалпы': 'kz', '29_өзгеріссіз': 'kz', '30_Тоқаев': 'kz', '31_жыл': 'kz', '32_бастала': 'kz', '33_сала': 'ambig', '34_бірнеше': 'kz', '35_заңға': 'kz', '36_қол': 'kz', '37_қойып': 'kz', '38_үлгерді': 'kz', '39_Цой': 'unk', '40_брифингте': 'kz', '41_сөз': 'kz', '42_сөйледі': 'kz', '43_Айтуынша': 'kz', '44_коронавирустың': 'kz', '45_таралуы': 'kz', '46_бойынша': 'kz', '47_жасыл': 'kz', '48_аймаққа': 'kz', '49_еніппіз': 'kz', '50_Сондай': 'kz', '51_ақ': 'kz', '52_елде': 'kz', '53_сайлау': 'kz', '54_жақындап': 'kz', '55_келеді': 'kz', '56_Бүгінгі': 'kz', '57_шығарылымда': 'kz', '58_жыл': 'kz', '59_басынан': 'kz', '60_бері': 'kz', '61_болып': 'kz', '62_жатқан': 'kz', '63_жаңалықтарды': 'kz', '64_талқылап': 'kz', '65_жылы': 'kz', '66_не': 'ambig', '67_өзгермек': 'kz', '68_деген': 'kz', '69_сұраққа': 'kz', '70_жауап': 'kz', '71_беретін': 'kz', '72_боламыз': 'kz'}
================================================================================
{'0_Балалар': 'kz', '1_суицидіне': 'kz', '2_кім': 'kz', '3_кінәлі': 'kz', '4_Фильмге': 'kz', '5_қазақша': 'kz', '6_субтитрлер': 'unk', '7_қосып': 'kz', '8_қойдық': 'kz', '9_Жақында': 'kz', '10_Тіл': 'kz', '11_кеспек': 'kz', '12_жоқ': 'kz', '13_және': 'kz', '14_За': 'ru', '15_нами': 'ambig', '16_уже': 'ru', '17_выехали': 'ru', '18_арнасының': 'kz', '19_Қазақстандағы': 'kz', '20_суицид': 'ambig', '21_мәселесіне': 'kz', '22_арналған': 'kz', '23_фильмінің': 'kz', '24_бірінші': 'kz', '25_бөлімі': 'kz', '26_шықты': 'kz', '27_Әсем': 'kz', '28_Жәпішева': 'kz', '29_мен': 'kz', '30_Дмитрий': 'ru', '31_Дубовицкий': 'unk', '32_бұл': 'kz', '33_бөлімде': 'kz', '34_балалар': 'kz', '35_мен': 'kz', '36_жасөспірімдердің': 'kz', '37_өз': 'kz', '38_өзіне': 'kz', '39_қол': 'kz', '40_жұмсауына': 'kz', '41_не': 'ambig', '42_себеп': 'kz', '43_екенін': 'kz', '44_анықтауға': 'kz', '45_тырысады': 'kz', '46_Қазақстан': 'kz', '47_ерлер': 'kz', '48_суициді': 'kz', '49_бойынша': 'kz', '50_төртінші': 'kz', '51_әйелдер': 'kz', '52_суициді': 'kz', '53_бойынша': 'kz', '54_жиырма': 'kz', '55_сегізінші': 'kz', '56_орында': 'kz', '57_Бұған': 'kz', '58_дейін': 'kz', '59_балалардың': 'kz', '60_өз': 'kz', '61_өзіне': 'kz', '62_қол': 'kz', '63_жұмсауы': 'kz', '64_бойынша': 'kz', '65_алғашқы': 'kz', '66_үштікке': 'kz', '67_кірген': 'kz', '68_Алайда': 'kz', '69_жылы': 'kz', '70_бұл': 'kz', '71_тізімнен': 'kz', '72_алшақтап': 'kz', '73_бар': 'ambig', '74_жоғы': 'kz', '75_орынға': 'kz', '76_жайғасты': 'kz', '77_Бұл': 'kz', '78_тақырып': 'kz', '79_көбі': 'kz', '80_үшін': 'kz', '81_жағымсыз': 'kz', '82_қызықсыз': 'kz', '83_болса': 'kz', '84_да': 'ambig', '85_әрқайсымыз': 'kz', '86_үшін': 'kz', '87_маңызды': 'kz', '88_Ата': 'kz', '89_ананың': 'kz', '90_баласын': 'kz', '91_түсінбеуі': 'kz', '92_бала': 'ambig', '93_өзін': 'kz', '94_жат': 'kz', '95_сезінуі': 'kz', '96_дұрыс': 'kz', '97_бағдар': 'kz', '98_беретін': 'kz', '99_маманның': 'kz', '100_болмауы': 'kz', '101_мектеп': 'kz', '102_психологтарының': 'kz', '103_жайы': 'kz', '104_және': 'kz', '105_өзге': 'kz', '106_де': 'ambig', '107_маңызды': 'kz', '108_проблемаларды': 'kz', '109_көре': 'kz', '110_аласыз': 'kz', '111_Балалардың': 'kz', '112_өз': 'kz', '113_өзіне': 'kz', '114_қол': 'kz', '115_жұмсауына': 'kz', '116_кім': 'kz', '117_кінәлі': 'kz', '118_Мемлекет': 'kz', '119_пе': 'ambig', '120_әлде': 'kz', '121_ата': 'kz', '122_ана': 'kz', '123_ма': 'kz', '124_Мемлекет': 'kz', '125_кінәлі': 'kz', '126_болса': 'kz', '127_неге': 'ambig', '128_ешкім': 'kz', '129_ешнәрсе': 'kz', '130_істемейді': 'kz', '131_Ата': 'kz', '132_ана': 'kz', '133_болса': 'kz', '134_олар': 'kz', '135_неден': 'kz', '136_қателесті': 'kz', '137_Қайтпек': 'kz', '138_керек': 'kz', '139_Неге': 'ambig', '140_еліміздегі': 'kz', '141_жасөспірімдер': 'kz', '142_мұны': 'kz', '143_тығырықтан': 'kz', '144_шығудың': 'kz', '145_жалғыз': 'kz', '146_жолы': 'kz', '147_көреді': 'kz', '148_Фильмде': 'kz', '149_осы': 'ambig', '150_сұрақтарға': 'kz', '151_жауап': 'kz', '152_беруге': 'kz'}
================================================================================

In [ ]:
exprmnt.add_probas(df_langproba, dropped_cols=[f'{METHOD}__probas'])
exprmnt.df.head()

,text,manual_tag,cld2__all_langs,cld2__best_lang,cld2__kaz,cld2__rus,cld3__best_lang,cld3__kaz,cld3__rus,langid__best_lang,...,fasttext__rus,tokens,spans,n_tokens,dict__best_lang,dict__token_annot,dict__unk,dict__kaz,dict__ambig,dict__rus
0,“Сандж” тәуелсіз зерттеу орталығының хабарлауы...,kz,kz,kz,0.99,0.0,kk,0.999996,0.0,kk,...,0.00001,"[Сандж, тәуелсіз, зерттеу, орталығының, хабарл...","[(1, 6), (8, 16), (17, 24), (25, 36), (37, 49)...",76,kz,"{'0_Сандж': 'unk', '1_тәуелсіз': 'kz', '2_зерт...",0.039474,0.828947,0.131579,0.000000
1,Заңгер Алексей Сонның консультациясына мына сі...,kz,kz-unk,kz,0.98,0.0,kk,0.999802,0.0,kk,...,0.00001,"[Заңгер, Алексей, Сонның, консультациясына, мы...","[(0, 6), (7, 14), (15, 21), (22, 38), (39, 43)...",96,kz,"{'0_Заңгер': 'kz', '1_Алексей': 'ru', '2_Сонны...",0.041667,0.812500,0.125000,0.020833
2,Шымкентте елуге жуық әйел әкімдік алдына жинал...,kz,kz,kz,0.99,0.0,kk,0.999981,0.0,kk,...,0.00001,"[Шымкентте, елуге, жуық, әйел, әкімдік, алдына...","[(0, 9), (10, 15), (16, 20), (21, 25), (26, 33...",30,kz,"{'0_Шымкентте': 'unk', '1_елуге': 'kz', '2_жуы...",0.066667,0.933333,0.000000,0.000000
3,Өте маңызды жобаға сұхбат кейіпкері ретінде кі...,kz,kz,kz,0.98,0.0,kk,0.999996,0.0,kk,...,0.00001,"[Өте, маңызды, жобаға, сұхбат, кейіпкері, реті...","[(0, 3), (4, 11), (12, 18), (19, 25), (26, 35)...",40,kz,"{'0_Өте': 'kz', '1_маңызды': 'kz', '2_жобаға':...",0.025000,0.925000,0.050000,0.000000
4,Айсұлтанның “құпиясы” Британиялық Financial ti...,kz-unk,kz,kz,0.98,0.0,kk,0.999997,0.0,kk,...,0.00001,"[Айсұлтанның, құпиясы, Британиялық, Financial,...","[(0, 11), (13, 20), (22, 33), (34, 43), (44, 4...",106,kz,"{'0_Айсұлтанның': 'kz', '1_құпиясы': 'kz', '2_...",0.018868,0.886792,0.075472,0.018868

In [ ]:
exprmnt.df[f'{METHOD}__best_lang'].value_counts()

dict__best_lang
ru       5434
kz       3676
ambig     403
unk       186
Name: count, dtype: int64

In [ ]:
exprmnt.df[exprmnt.df[f'{METHOD}__best_lang']=='ambig'][f'{METHOD}__token_annot'].head().to_list()

[{'0_Алматы': 'kz',
  '1_площадь': 'ru',
  '2_Республики': 'ambig',
  '3_Фото': 'ambig'},
 {'0_Неге': 'ambig', '1_не': 'ambig', '2_емес': 'kz'},
 {'0_Морда': 'ambig',
  '1_как': 'ambig',
  '2_у': 'ambig',
  '3_спившегося': 'ru',
  '4_гитлера': 'ru'},
 {'0_Я': 'ru',
  '1_не': 'ambig',
  '2_таксист': 'ambig',
  '3_у': 'ambig',
  '4_меня': 'ru',
  '5_такая': 'ru',
  '6_позиция': 'ambig'},
 {'0_АКТ': 'ambig',
  '1_емес': 'kz',
  '2_акт': 'ambig',
  '3_Это': 'ru',
  '4_не': 'ambig',
  '5_акроним': 'ambig',
  '6_девочки': 'ru'}]

In [ ]:
exprmnt.df[[f'{METHOD}__kaz', f'{METHOD}__rus', f'{METHOD}__ambig', f'{METHOD}__unk']].describe()

         dict__kaz    dict__rus  dict__ambig    dict__unk
count  9699.000000  9699.000000  9699.000000  9699.000000
mean      0.336175     0.392021     0.202695     0.069109
std       0.408535     0.325684     0.150960     0.111178
min       0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.083333     0.000000
50%       0.029412     0.500000     0.192308     0.019802
75%       0.828348     0.666667     0.300000     0.100000
max       1.000000     1.000000     1.000000     1.000000

In [ ]:
exprmnt.save_experiment(path=save_to_path)

In [ ]:
exprmnt.df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9699 entries, 0 to 9698
Data columns (total 38 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   text                        9699 non-null   object
 1   manual_tag                  9699 non-null   object
 2   cld2__all_langs             9699 non-null   object
 3   cld2__best_lang             9699 non-null   object
 4   cld2__kaz                   9699 non-null   float64
 5   cld2__rus                   9699 non-null   float64
 6   cld3__best_lang             9699 non-null   object
 7   cld3__kaz                   9699 non-null   float64
 8   cld3__rus                   9699 non-null   float64
 9   langid__best_lang           9699 non-null   object
 10  langid__kaz                 9699 non-null   float64
 11  langid__rus                 9699 non-null   float64
 12  lingua__best_lang           9699 non-null   object
 13  lingua__kaz                 9699 non-null   float64
 14  lingua__rus                 9699 non-null   float64
 15  lingua__langs               9699 non-null   object
 16  lingua__all_langs           9699 non-null   object
 17  mediapipe__best_lang        9699 non-null   object
 18  mediapipe__kaz              9699 non-null   float64
 19  mediapipe__rus              9699 non-null   float64
 20  fast_langdetect__best_lang  9699 non-null   object
 21  fast_langdetect__kaz        9699 non-null   float64
 22  fast_langdetect__rus        9699 non-null   float64
 23  glotlid__best_lang          9699 non-null   object
 24  glotlid__kaz                9699 non-null   float64
 25  glotlid__rus                9699 non-null   float64
 26  fasttext__best_lang         9699 non-null   object
 27  fasttext__kaz               9699 non-null   float64
 28  fasttext__rus               9699 non-null   float64
 29  tokens                      9699 non-null   object
 30  spans                       9699 non-null   object
 31  n_tokens                    9699 non-null   int64
 32  dict__best_lang             9699 non-null   object
 33  dict__token_annot           9699 non-null   object
 34  dict__unk                   9699 non-null   float64
 35  dict__kaz                   9699 non-null   float64
 36  dict__ambig                 9699 non-null   float64
 37  dict__rus                   9699 non-null   float64
dtypes: float64(20), int64(1), object(17)
memory usage: 2.8+ MB